version: "3.3"

services:
    hr:
        build: .
        restart: always
        networks:
            - db
            - eureka
        environment:
            SPRING_PROFILES_ACTIVE: docker
            JAVA_OPTS: "-Xms256M -Xmx256M"
    db:
        image: postgres:12.1-alpine
        expose:
          - 5432
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - db:/var/lib/postgresql/data
        networks:
            - db
        restart: always

volumes:
    db:
        external: false

networks:
    db:
        external: false
    eureka:
        external: true
