version: "3.3"

services:
    db:
        image: postgres:12.1-alpine
        ports:
            - ${DB_PORT:-5432}:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: postgres
        volumes:
            - db:/var/lib/postgresql/data

volumes:
    db:
        external: false
